# Node.js Async Function Best Practices (Nh·ªØng kinh nghi·ªám hay v·ªõi h√†m _async_ trong NodeJS)
K·ªÉ t·ª´ phi√™n b·∫£n **NodeJS** 7.6, **NodeJS** "chuy√™n ch·ªü" v·ªõi m·ªôt phi√™n b·∫£n _engine V8_ m·ªõi (V8 version 5.5) ƒë∆∞·ª£c h·ªó tr·ª£ x·ª≠ l√Ω c√°c h√†m b·∫•t ƒë·ªìng b·ªô v·ªõi t·ª´ kh√≥a _async_. Th√™m v√†o ƒë√≥, Ng√†y 31/10/2017 v·ª´a qua NodeJS 8 ch√≠nh th·ª©c tr·ªù th√†nh **LTS version** (Long Term Support - phi√™n b·∫£n ƒë∆∞·ª£c h·ªó tr·ª£ d√†i h·∫°n) c·ªßa LTS team NodeJS. V√¨ v·∫≠y, kh√¥ng c√≥ l√Ω do g√¨ kh√¥ng b·∫Øt ƒë·∫ßu s·ª≠ d·ª•ng c√°c h√†m _async_ trong c·∫•u tr√∫c code c·ªßa b·∫°n. Trong b√†i vi·∫øt n√†y, gi·ªõi thi·ªáu ng·∫Øn g·ªçn cho b·∫°n h√†m _async_ l√† g√¨, v√† c√°i c√°ch m√† n√≥ s·∫Ω l√†m thay ƒë·ªïi c√°ch ch√∫ng ta vi·∫øt c√°c ·ª©ng d·ª•ng **NodeJS**.

## H√†m ASYNC l√† g√¨?

C√°c h√†m _async_ cho ph√©p b·∫°n vi·∫øt c√°c ƒëo·∫°n code d·ª±a tr√™n **Promise** tr√¥ng nh∆∞ l√† n√≥ ƒë∆∞·ª£c x·ª≠ l√Ω ƒë·ªìng b·ªô v·∫≠y (l·∫ßn l∆∞·ª£t t·ª´ tr√™n xu·ªëng d∆∞·ªõi). M·ªôt l·∫ßn b·∫°n ƒë·ªãnh nghƒ©a m·ªôt h√†m s·ª≠ d·ª•ng t·ª´ kh√≥a _async_ (g·ªçi l√† _async function_), sau ƒë√≥ b·∫°n s·ª≠ d·ª•ng t·ª´ kh√≥a _await_ b√™n trong th√¢n h√†m ƒë√≥. 

Khi _async function_ ƒë∆∞·ª£c g·ªçi, n√≥ tr·∫£ v·ªÅ m·ªôt **Promise**. Khi _async function_ tr·∫£ v·ªÅ m·ªôt gi√° tr·ªã, **Promise** nh·∫≠n tr·∫°ng th√°i _fullfilled_, c√≤n n·∫øu _async function_ tr·∫£ v·ªÅ _error_, **Promise** nh·∫≠n tr·∫°ng th√°i _rejected_.

T·ª´ kh√≥a _await_ c√≥ th·ªÉ ƒë∆∞·ª£c s·ª≠ d·ª•ng ƒë·ªÉ ƒë·ª£i m·ªôt **Promise** (c√°i m√† ƒë∆∞·ª£c resolved v√† tr·∫£ v·ªÅ tr·∫°ng th√°i _fullfilled_). N·∫øu m·ªôt gi√° tr·ªã (_value_) truy·ªÅn t·ªõi t·ª´ kh√≥a _await_ kh√¥ng ph·∫£i l√† m·ªôt **Promise**, n√≥ chuy·ªÉn ƒë·ªïi _value_ th√†nh m·ªôt resolve Promise.

```js
const rp = require('request-promise')
async function main () {
  const result = await rp('https://google.com')
  const twenty = await 20
  
  // sleeeeeeeeping  for a second üí§
  await new Promise (resolve => {
    setTimeout(resolve, 1000)
  })
  return result
}
main()
  .then(console.log)
  .catch(console.error)

```
## Di tr√∫ (Migrating) t·ªõi c√°c h√†m _async_

N·∫øu c√°c ·ª©ng d·ª•ng **NodeJS** c·ªßa b·∫°n ƒë√£ ƒëang s·ª≠ d·ª•ng **Promises**, b·∫°n ch·ªâ vi·ªác b·∫Øt ƒë·∫ßu _awaiting_ c√°c **Promise** c·ªßa b·∫°n thay v√¨ n·ªëi chu·ªói (chaining) ch√∫ng. 

N·∫øu c√°c ·ª©ng d·ª•ng c·ªßa b·∫°n ƒëang x√¢y d·ª±ng s·ª≠ d·ª•ng _callbacks_, vi·ªác chuy·ªÉn sang c√°c h√†m 
_async_ n√™n ti·∫øn h√†nh d·∫ßn d·∫ßn. B·∫°n c√≥ th·ªÉ b·∫Øt ƒë·∫ßu th√™m c√°c t√¨nh nƒÉng m·ªõi b·∫±ng vi·ªác s·ª≠ d·ª•ng k·ªπ thu·∫≠t m·ªõi n√†y (_async/await_). N·∫øu b·∫°n ph·∫£i s·ª≠ d·ª•ng c√°c ph·∫ßn c≈© h∆°n c·ªßa ·ª©ng d·ª•ng, b·∫°n c√≥ th·ªÉ ƒë∆°n gi·∫£n b·ªçc (wrap) ch√∫ng trong c√°c **Promises**.
ƒê·ªÉ l√†m v·∫≠y, b·∫°n c√≥ th·ªÉ s·ª≠ d·ª•ng ph∆∞∆°ng th·ª©c x√¢y d·ª±ng s·∫µn (built-in method) _util.promisify_

```js
    const util = require('util')
const {readFile} = require('fs')
const readFileAsync = util.promisify(readFile)
async function main () {
  const result = await readFileAsync('.gitignore')
  return result
}
main()
  .then(console.log)
  .catch(console.error)
```
## Th·ª±c h√†nh t·ªët h∆°n cho c√°c h√†m _**async**_

### #S·ª≠ d·ª•ng c√°c h√†m _async_ v·ªõi _express_

B·ªüi v√¨ _express_ h·ªó tr·ª£ **Promises**, s·ª≠ d·ª•ng c√°c h√†m _async_ v·ªõi _express_ ƒë∆°n gi·∫£n nh∆∞ sau: 
```js
const express = require('express')
const app = express()
app.get('/', async (request, response) => {
  // awaiting Promises here
  // if you just await a single promise, you could simply return with it,
  // no need to await for it
  const result = await getContent()
  response.send(result)
})
app.listen(process.env.PORT)
```

Ch·ªânh s·ª≠a 1: Nh∆∞ l√† Keith Smith ƒë√£ ch·ªâ ra, v√≠ d·ª• tr√™n c√≥ 1 v·∫•n ƒë·ªÅ ph√°t sinh nghi√™m tr·ªçng - N·∫øu nh∆∞ **Promise** nh·∫≠n tr·∫°ng th√°i _rejected_, _the express route handle_ (x·ª≠ l√Ω ƒëi·ªÅu h∆∞·ªõng c·ªßa _express_) s·∫Ω b·ªã treo, b·ªüi v√¨ kh√¥ng c√≥ x·ª≠ l√Ω l·ªói ƒë∆∞·ª£c g·ªçi ra.

ƒê·ªÉ x·ª≠ l√Ω v·∫•n ƒë·ªÅ ƒë√≥, b·∫°n n√™n b·ªçc (wrap) c√°c x·ª≠ l√Ω b·∫•t ƒë·ªìng b·ªô ƒë√≥ trong m·ªôt h√†m x·ª≠ l√Ω l·ªói:
```js
  const awaitHandlerFactory = (middleware) => {
  return async (req, res, next) => {
    try {
      await middleware(req, res, next)
    } catch (err) {
      next(err)
    }
  }
}
// and use it this way:
app.get('/', awaitHandlerFactory(async (request, response) => {
  const result = await getContent()
  response.send(result)
}))
```
## Parallel execution (Th·ª±c thi song h√†nh)

T∆∞·ªüng t∆∞·ª£ng b·∫°n ƒëang l√†m vi·ªác tr√™n m·ªôt c√°i g√¨ ƒë√≥ t∆∞∆°ng t·ª± nh∆∞, khi m·ªôt t√°c v·ª• c·∫ßn 2 ƒë·∫ßu v√†o (_input_), m·ªôt t·ª´ database, v√† m·ªôt t·ª´ d·ªãch v·ª• b√™n ngo√†i kh√°c:

```js
  async function main () {
  const user = await Users.fetch(userId)
  const product = await Products.fetch(productId)
  await makePurchase(user, product)
}
```

Trong tr∆∞·ªùng h·ª£p n√†y, m·ªçi vi·ªác di·ªÖn ra nh∆∞ sau:

  * ƒê·∫ßu ti√™n l√† l·∫•y v·ªÅ t√†i nguy√™n _user resource_ (th√¥ng tin v·ªÅ _user_),
  * sau ƒë√≥ l·∫•y v·ªÅ _product resource_ (th√¥ng tin v·ªÅ s·∫£n ph·∫©m),
  * cu·ªëi c√πng l√† th·ª±c thi h√†m _makePurchase_

Nh∆∞ b·∫°n th·∫•y l√†, b·∫°n c√≥ th·ªÉ l√†m 2 vi·ªác ƒë·∫ßu m·ªôt c√°ch song h√†nh (parallel), b·ªüi v√¨ ch√∫ng kh√¥ng c√≥ s·ª± ph·ª• thu·ªôc n√†o v√†o nhau c·∫£. ƒê·ªÉ l√†m ƒëi·ªÅu n√†y, b·∫°n n√™n s·ª≠ d·ª•ng ph∆∞∆°ng th·ª©c _Promise.all_ :
```js
async function main () {
  const [user, product] = await Promise.all([
    Users.fetch(userId),
    Products.fetch(productId)
  ])
  await makePurchase(user, product)
}
```
Trong m·ªôt v√†i tr∆∞·ªùng h·ª£p, b·∫°n ch·ªâ c·∫ßn k·∫øt qu·∫£ tr·∫£ v·ªÅ c·ªßa _resolving Promise_ nhanh nh·∫•t - trong tr∆∞·ªùng h·ª£p n√†y, b·∫°n c√≥ th·ªÉ s·ª≠ d·ª•ng ph∆∞∆°ng th·ª©c Promise.race.

## Error handling (X·ª≠ l√Ω l·ªói)

Xem x√©t code v√≠ d·ª• sau ƒë√¢y:

```js
async function main () {
  await new Promise((resolve, reject) => {
    reject(new Error('üí•'))
  })
}
main()
  .then(console.log)
```

Khi ch·∫°y ƒëo·∫°n code tr√™n, b·∫°n s·∫Ω nh·∫≠n ƒë∆∞·ª£c m·ªôt th√¥ng b√°o trong _terminal_ c·ªßa b·∫°n ki·ªÉu nh∆∞:

```
(node:69738) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: üí•
(node:69738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Trong c√°c b·∫£n m·ªõi h∆°n c·ªßa **NodeJs**, N·∫øu nh∆∞ _Promise rejection_ kh√¥ng ƒë∆∞·ª£c x·ª≠ l√Ω, n√≥ s·∫Ω mang xu·ªëng to√†n b·ªô ti·∫øn tr√¨nh **NodeJS**. B·ªüi v·∫≠y, b·∫°n n√™n s·ª≠ d·ª•ng c√°c kh·ªëi _try-catch_ khi c·∫ßn thi·∫øt:

```js
const util = require('util')
async function main () {
  try {
    await new Promise((resolve, reject) => {
      reject(new Error('üí•'))
    })
  } catch (err) {
    // handle error case
    // maybe throwing is okay depending on your use-case
  }
}
main()
  .then(console.log)
  .catch(console.error)
```

## More complex control flows(C√°c x·ª≠ l√Ω ph·ª©c t·∫°p h∆°n)

M·ªôt trong c√°c th∆∞ vi·ªán x·ª≠ l√Ω qu√° tr√¨nh b·∫•t ƒë·ªìng b·ªô ƒë·∫ßu ti√™n cho NodeJS l√† _async_ ƒë∆∞·ª£c t·∫°o b·ªüi Caolan McMahon. N√≥ cung c·∫•p c√°c h·ªó tr·ª£ b·∫•t ƒë·ªìng b·ªô, nh∆∞ l√†: 

  * mapLitmit,
  * filterLimit,
  * concatLimit,
  * or priorityQueue
N·∫øu b·∫°n kh√¥ng mu·ªën "ph√°t minh l·∫°i b√°nh xe" v√† th·ª±c hi·ªán l·∫°i c√°c logic t∆∞∆°ng t·ª±, v√† b·∫°n c≈©ng mu·ªën ph·ª• thu·ªôc v√†o th∆∞ vi·ªán _battle-tested_ c√≥ 50 tri·ªáu l∆∞·ª£t t·∫£i v·ªÅ m·ªôt th√°ng, b·∫°n c√≥ th·ªÉ ƒë∆°n gi·∫£n s·ª≠ d·ª•ng l·∫°i nh·ªØng h√†m n√†y v·ªõi c√°c h√†m _async_ c≈©ng t·ªët, s·ª≠ d·ª•ng ph∆∞∆°ng th·ª©c _util.promisify_ :
```js
reinvent the wheel and implement the same logic again, and you also want to depend on a battle-tested library downloaded 50 million times a month, you can simply reuse these functions with async functions as well, using the util.promisify method:

const util = require('util')
const async = require('async')
const numbers = [
  1, 2, 3, 4, 5
]
mapLimitAsync = util.promisify(async.mapLimit)
async function main () {
  return await mapLimitAsync(numbers, 2, (number, done) => {
    setTimeout(function () {
      done(null, number * 2)
    }, 100)
  })
}
main()
  .then(console.log)
  .catch(console.error)
```

## Next up

T√¥i hi v·ªçng b·∫°n th√≠ch b√†i vi·∫øt n√†y v√† h·ªçc ƒë∆∞·ª£c nhi·ªÅu th·ª©! (:smile). 

D·∫´n ngu·ªìn: [https://nemethgergely.com/async-function-best-practices/](https://nemethgergely.com/async-function-best-practices/)
